<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [85]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [106]:
trip_data_raw = pd.read_csv('chicago_taxi_data.csv', index_col=None, nrows=20, dtype={
    'trip_ID' : 'str',
    'taxi_ID' : 'str',
#    'trip_start_timestamp' : 'datetime64[ms]',
    'payment_type' : 'category',
    'company' : 'category'
})

In [107]:
trip_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 23 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   trip_id                     20 non-null     object
 1   taxi_id                     20 non-null     object
 2   trip_start_timestamp        20 non-null     object
 3   trip_end_timestamp          20 non-null     object
 4   trip_seconds                20 non-null     int64
 5   trip_miles                  20 non-null     float64
 6   pickup_census_tract         7 non-null      float64
 7   dropoff_census_tract        7 non-null      float64
 8   pickup_community_area       9 non-null      float64
 9   dropoff_community_area      9 non-null      float64
 10  fare                        20 non-null     float64
 11  tips                        20 non-null     float64
 12  tolls                       20 non-null     float64
 13  extras                      20 non-null     float64
 14  trip_total                  20 non-null     float64
 15  payment_type                20 non-null     category
 16  company                     20 non-null     category
 17  pickup_centroid_latitude    9 non-null      float64
 18  pickup_centroid_longitude   9 non-null      float64
 19  pickup_centroid_location    9 non-null      object
 20  dropoff_centroid_latitude   9 non-null      float64
 21  dropoff_centroid_longitude  9 non-null      float64
 22  dropoff_centroid_location   9 non-null      object
dtypes: category(2), float64(14), int64(1), object(6)
memory usage: 3.9+ KB

In [109]:
trip_data_raw.head(20)

,trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,pickup_census_tract,dropoff_census_tract,pickup_community_area,dropoff_community_area,...,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location
0,d7bf7332e89c6597d682495ac78a325c2ed4183f,d0653a3c1a990641559a9e6e7c0e07db3765fe11e48ad7...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,1080,3.7,NaN,NaN,NaN,NaN,...,0.0,17.55,Credit Card,Choice Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
1,c8769473b60b18f700afce0f812f6d80c3616ca7,21c5d83c2cb73035c6c4d35da452ff1714aff86f5efb32...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,240,0.3,NaN,NaN,NaN,NaN,...,1.0,5.50,Cash,Choice Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
2,c52d1cd141c3036d091ed85cbf7a973cc5c1243e,a6c3cb7ab4c037a7db9e2fd3513f28e0ff17c8547a70bd...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,60,0.4,NaN,NaN,NaN,NaN,...,0.0,3.75,Cash,Dispatch Taxi Affiliation,NaN,NaN,NaN,NaN,NaN,NaN
3,b5714d1d2118642f789ab0fec542f597f986c251,d8238dd38b47fc0268e0bd92bba094676752dfefeafea9...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,840,2.7,NaN,NaN,NaN,NaN,...,1.0,11.50,Cash,Star North Management LLC,NaN,NaN,NaN,NaN,NaN,NaN
4,0352e306e7cc33a455c3be20764ad2ce9881216a,7698f29134c0f429f821af4e89a8f769b85e376bd37b3c...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,0,0.0,NaN,NaN,NaN,NaN,...,0.0,14.50,Credit Card,Suburban Dispatch LLC,NaN,NaN,NaN,NaN,NaN,NaN
5,594e15b562a96bd7cafac7211fb71ff4331ee803,45ae9d400abb9327b717e4d8849843ad78e40d7a72e324...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,720,6.5,NaN,NaN,NaN,NaN,...,4.0,22.00,Cash,Dispatch Taxi Affiliation,NaN,NaN,NaN,NaN,NaN,NaN
6,2896540c849ebc75c05af74af4b969759eaa5fa3,3fb54b9070b703bd28358e704311d7fe8afb6950881654...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,660,0.5,NaN,NaN,NaN,NaN,...,0.0,7.25,Cash,KOAM Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
7,71b0b8528bb56e921997c6de6190257fe2e58dcd,0c722e1c967f929866e205cde7aefefae970c66351c0db...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,0,0.0,NaN,NaN,NaN,NaN,...,0.0,44.00,Credit Card,Suburban Dispatch LLC,NaN,NaN,NaN,NaN,NaN,NaN
8,047773cc8210996a8f88ad023c79c86bba5423de,9454a3cb5d7e8ef84ca9bfff9f1a5d235021fef66b41a8...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,0,0.0,NaN,NaN,NaN,NaN,...,0.0,11.00,Credit Card,Suburban Dispatch LLC,NaN,NaN,NaN,NaN,NaN,NaN
9,80447e42e7ad6f32607bdcbba79725b3ea8bc094,5e2cdbf8e29532911397d269fc7777dbe01700c6dbc517...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,480,0.2,NaN,NaN,NaN,NaN,...,0.0,5.75,Cash,Choice Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
10,a6673cb2888d07e963a35fedd3a635ac1b11c3d4,21c5d83c2cb73035c6c4d35da452ff1714aff86f5efb32...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,420,0.7,NaN,NaN,NaN,NaN,...,1.0,9.00,Credit Card,Choice Taxi Association,NaN,NaN,NaN,NaN,NaN,NaN
11,0a0a2ca50df85134ce34f0c2c7bda6e78ca2a52c,bbe793119144e0bd97a4268af2a28ed0f3dad49545592c...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,180,0.0,1.703108e+10,1.703132e+10,8.0,32.0,...,1.0,7.00,Credit Card,Blue Ribbon Taxi Association Inc.,41.892508,-87.626215,"{'type': 'Point', 'coordinates': [-87.62621490...",41.884987,-87.620993,"{'type': 'Point', 'coordinates': [-87.62099291..."
12,7c46253c55f14a47b0bdd41baa1abc0366d64c58,99ab5248605aa4afb82e6be7d50d531fd8e423980159bb...,2018-01-01T00:15:00.000,2018-01-01T00:15:00.000,120,0.7,NaN,NaN,5.0,5.0,...,2.0,6.75,Cash,Star North Management LLC,41.947792,-87.683835,"{'type': 'Point', 'coordinates': [-87.68383494...",41.947792,-87.683835,"{'type': 'Point', 'coordinates': [-87.68383494..."
13,ac1fae1544d7804f13fbf657cb058ba91a983fea,847cf962bd6f62040673e6c24c24940aeb2d7fdaa54677...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,960,2.6,1.703107e+10,1.703108e+10,7.0,8.0,...,0.0,11.00,Cash,Taxi Affiliation Services,41.914616,-87.631717,"{'type': 'Point', 'coordinates': [-87.63171736...",41.907520,-87.626659,"{'type': 'Point', 'coordinates': [-87.62665890..."
14,b7e939ebeb25eee245afd346ff63adeb0139e6d7,efd204f38a83a59df5bf4a1fe004aa291183e235ee40ee...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,1260,0.0,1.703108e+10,1.703108e+10,8.0,8.0,...,2.5,13.00,Cash,Star North Management LLC,41.892073,-87.628874,"{'type': 'Point', 'coordinates': [-87.62887415...",41.891972,-87.612945,"{'type': 'Point', 'coordinates': [-87.61294541..."
15,29f96067e9339e477e983efddd6395a2a8557c45,92725f67f872c1d48d77ffa906f837c6a5f20f5a597a8d...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,660,0.0,1.703108e+10,1.703124e+10,8.0,24.0,...,1.5,12.50,Cash,Blue Ribbon Taxi Association Inc.,41.907492,-87.635760,"{'type': 'Point', 'coordinates': [-87.63576009...",41.899590,-87.674719,"{'type': 'Point', 'coordinates': [-87.67471913..."
16,967a2dad921818b54a19b27a9c67310f7cfb9f2c,609fa4bfe241aacb61e59c5b52abcbbd467b8e71d53dd9...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,300,0.9,1.703108e+10,1.703108e+10,8.0,8.0,...,1.5,7.00,Cash,Choice Taxi Association,41.892042,-87.631864,"{'type': 'Point', 'coordinates': [-87.63186394...",41.891972,-87.612945,"{'type': 'Point', 'coordinates': [-87.61294541..."
17,a6ecf116e5ed732519617bf003100af806fa1f02,1061d157b2a98a1b1e7871639b836de5fb521101d08d73...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,180,0.8,NaN,NaN,6.0,6.0,...,2.0,7.00,Cash,Taxi Affiliation Services,41.944227,-87.655998,"{'type': 'Point', 'coordinates': [-87.65599818...",41.944227,-87.655998,"{'type': 'Point', 'coordinates': [-87.65599818..."
18,e4bcdde34928852b0d8ed4641f4c0533e06a29ab,c38a211cb84a44a24e959493d5842a48dd150b1e947b30...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,1320,0.2,1.703107e+10,1.703184e+10,7.0,32.0,...,1.5,16.75,Cash,Taxi Affiliation Services,41.921855,-87.646211,"{'type': 'Point', 'coordinates': [-87.64621097...",41.880994,-87.632746,"{'type': 'Point', 'coordinates': [-87.63274648..."
19,649cae1facf2431d6e5578fec8cadfef46d79841,15dd49f5b45c96f8f6dd62e5a50224a9b8abd8bc891648...,2018-01-01T00:15:00.000,2018-01-01T00:30:00.000,900,0.9,1.703108e+10,1.703108e+10,8.0,8.0,...,1.0,9.75,Cash,Choice Taxi Association,41.902788,-87.626146,"{'type': 'Point', 'coordinates': [-87.62614558...",41.892508,-87.626215,"{'type': 'Point', 'coordinates': [-87.62621490..."

trip_id,taxi_id,trip_start_timestamp,trip_end_timestamp,trip_seconds,trip_miles,fare,tips,tolls,extras,trip_total,payment_type,company,pickup_centroid_latitude,pickup_centroid_longitude,pickup_centroid_location,dropoff_centroid_latitude,dropoff_centroid_longitude,dropoff_centroid_location

In [110]:
trip_data_raw.columns

Index(['trip_id', 'taxi_id', 'trip_start_timestamp', 'trip_end_timestamp',
       'trip_seconds', 'trip_miles', 'pickup_census_tract',
       'dropoff_census_tract', 'pickup_community_area',
       'dropoff_community_area', 'fare', 'tips', 'tolls', 'extras',
       'trip_total', 'payment_type', 'company', 'pickup_centroid_latitude',
       'pickup_centroid_longitude', 'pickup_centroid_location',
       'dropoff_centroid_latitude', 'dropoff_centroid_longitude',
       'dropoff_centroid_location'],
      dtype='object')